// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvH6Ef6SoY9yK18r6Zys1y6unugcA8fA',
    appId: '1:631936371290:web:600ca3f20a61b0c33e6663',
    messagingSenderId: '631936371290',
    projectId: 'lawapp-c073e',
    authDomain: 'lawapp-c073e.firebaseapp.com',
    databaseURL: 'https://lawapp-c073e-default-rtdb.firebaseio.com',
    storageBucket: 'lawapp-c073e.appspot.com',
    measurementId: 'G-5RFBFBP65W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChB40Ib-Sm32y9cgXX-2CL84PSRiCIIAU',
    appId: '1:631936371290:android:e81c3f26246f0adf3e6663',
    messagingSenderId: '631936371290',
    projectId: 'lawapp-c073e',
    databaseURL: 'https://lawapp-c073e-default-rtdb.firebaseio.com',
    storageBucket: 'lawapp-c073e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7RZ-qxezT1Bg_mVbgX9u0jNxOZUJdXpU',
    appId: '1:631936371290:ios:dde4cdc7625028543e6663',
    messagingSenderId: '631936371290',
    projectId: 'lawapp-c073e',
    databaseURL: 'https://lawapp-c073e-default-rtdb.firebaseio.com',
    storageBucket: 'lawapp-c073e.appspot.com',
    iosClientId: '631936371290-6jeapfqulqddght6qat15mcg37k37tut.apps.googleusercontent.com',
    iosBundleId: 'com.example.law',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7RZ-qxezT1Bg_mVbgX9u0jNxOZUJdXpU',
    appId: '1:631936371290:ios:dde4cdc7625028543e6663',
    messagingSenderId: '631936371290',
    projectId: 'lawapp-c073e',
    databaseURL: 'https://lawapp-c073e-default-rtdb.firebaseio.com',
    storageBucket: 'lawapp-c073e.appspot.com',
    iosClientId: '631936371290-6jeapfqulqddght6qat15mcg37k37tut.apps.googleusercontent.com',
    iosBundleId: 'com.example.law',
  );
}
